project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "con-gen-csu"
  author: "Eric C. Anderson"
  date: "9/19/2022"
  chapters:
    - index.qmd
    - nmfs-bioinf/open-on-demand-alpine.qmd
    - nmfs-bioinf/quick-unix-review.qmd
    - nmfs-bioinf/shell-prog.qmd
    - nmfs-bioinf/awk-intro.qmd
    - nmfs-bioinf/scripts-and-functions.qmd
    - nmfs-bioinf/slurm.qmd
    - nmfs-bioinf/sbatch.qmd
    - nmfs-bioinf/slurm-arrays.qmd
    - nmfs-bioinf/sequence-alignment.qmd
    - nmfs-bioinf/bioinf-formats.qmd
    - nmfs-bioinf/snake.qmd
    - nmfs-bioinf/snakemake-relevant-python.qmd
    - nmfs-bioinf/snakemake-embellishments.qmd
  sidebar:
    logo: nmfs-bioinf/quarto-static/fisheries_header_logo_jul2019.png
  repo-url: https://github.com/eriqande/con-gen-csu
  issue-url: https://github.com/eriqande/con-gen-csu/issues/new/choose
  repo-actions: [edit, issue]


format:
  html:
    theme: cosmo


editor: source
