
executor: slurm
default-resources:
  - runtime=480   # must be specified in minutes
  - mem_mb=4800
  - tmpdir="results/snake-tmp"
  - slurm_partition=standard
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 50
local-cores: 1
latency-wait: 60
cores: 2400
jobs: 950
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
rerun-trigger: mtime

