<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>con-gen-csu - 9&nbsp; Bioinformatic file formats</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../nmfs-bioinf/sequence-alignment.html" rel="next">
<link href="../nmfs-bioinf/snake.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../nmfs-bioinf/bioinf-formats.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bioinformatic file formats</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../nmfs-bioinf/quarto-static/fisheries_header_logo_jul2019.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">con-gen-csu</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/quick-unix-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Quick Unix Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/shell-prog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Shell Programming</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/awk-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">A Brief <code>awk</code> Intro</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/scripts-and-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bash scripts and functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/slurm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sedna and SLURM intro</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/sbatch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Submitting jobs with <code>sbatch</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/slurm-arrays.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Slurm Job Arrays</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/snake.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Snakemake Tutorial Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/bioinf-formats.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bioinformatic file formats</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../nmfs-bioinf/sequence-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequence alignment and handling BAM files</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sequences" id="toc-sequences" class="nav-link active" data-scroll-target="#sequences"><span class="header-section-number">9.1</span> Sequences</a></li>
  <li><a href="#fastq" id="toc-fastq" class="nav-link" data-scroll-target="#fastq"><span class="header-section-number">9.2</span> FASTQ</a>
  <ul class="collapse">
  <li><a href="#illumina-ids" id="toc-illumina-ids" class="nav-link" data-scroll-target="#illumina-ids"><span class="header-section-number">9.2.1</span> Line 1: Illumina identifier lines</a></li>
  <li><a href="#bqscores" id="toc-bqscores" class="nav-link" data-scroll-target="#bqscores"><span class="header-section-number">9.2.2</span> Line 4: Base quality scores</a></li>
  </ul></li>
  <li><a href="#fasta" id="toc-fasta" class="nav-link" data-scroll-target="#fasta"><span class="header-section-number">9.3</span> FASTA</a>
  <ul class="collapse">
  <li><a href="#genomic-ranges" id="toc-genomic-ranges" class="nav-link" data-scroll-target="#genomic-ranges"><span class="header-section-number">9.3.1</span> Genomic ranges</a></li>
  <li><a href="#extracting-genomic-ranges-from-a-fasta-file" id="toc-extracting-genomic-ranges-from-a-fasta-file" class="nav-link" data-scroll-target="#extracting-genomic-ranges-from-a-fasta-file"><span class="header-section-number">9.3.2</span> Extracting genomic ranges from a FASTA file</a></li>
  <li><a href="#downloading-reference-genomes-from-ncbi" id="toc-downloading-reference-genomes-from-ncbi" class="nav-link" data-scroll-target="#downloading-reference-genomes-from-ncbi"><span class="header-section-number">9.3.3</span> Downloading reference genomes from NCBI</a></li>
  </ul></li>
  <li><a href="#sambamfiles" id="toc-sambamfiles" class="nav-link" data-scroll-target="#sambamfiles"><span class="header-section-number">9.4</span> Alignments</a>
  <ul class="collapse">
  <li><a href="#how-might-i-align-to-thee-let-me-count-the-ways" id="toc-how-might-i-align-to-thee-let-me-count-the-ways" class="nav-link" data-scroll-target="#how-might-i-align-to-thee-let-me-count-the-ways"><span class="header-section-number">9.4.1</span> How might I align to thee? Let me count the ways…</a></li>
  <li><a href="#play-with-simple-alignments" id="toc-play-with-simple-alignments" class="nav-link" data-scroll-target="#play-with-simple-alignments"><span class="header-section-number">9.4.2</span> Play with simple alignments</a></li>
  <li><a href="#sam-flags" id="toc-sam-flags" class="nav-link" data-scroll-target="#sam-flags"><span class="header-section-number">9.4.3</span> SAM Flags</a></li>
  <li><a href="#cigar" id="toc-cigar" class="nav-link" data-scroll-target="#cigar"><span class="header-section-number">9.4.4</span> The CIGAR string</a></li>
  <li><a href="#the-seq-and-qual-columns" id="toc-the-seq-and-qual-columns" class="nav-link" data-scroll-target="#the-seq-and-qual-columns"><span class="header-section-number">9.4.5</span> The SEQ and QUAL columns</a></li>
  <li><a href="#sam-headers" id="toc-sam-headers" class="nav-link" data-scroll-target="#sam-headers"><span class="header-section-number">9.4.6</span> SAM File Headers</a></li>
  <li><a href="#the-bam-format" id="toc-the-bam-format" class="nav-link" data-scroll-target="#the-bam-format"><span class="header-section-number">9.4.7</span> The BAM format</a></li>
  <li><a href="#quick-self-study" id="toc-quick-self-study" class="nav-link" data-scroll-target="#quick-self-study"><span class="header-section-number">9.4.8</span> Quick self study</a></li>
  </ul></li>
  <li><a href="#variants" id="toc-variants" class="nav-link" data-scroll-target="#variants"><span class="header-section-number">9.5</span> Variants</a>
  <ul class="collapse">
  <li><a href="#vcf-format-the-body" id="toc-vcf-format-the-body" class="nav-link" data-scroll-target="#vcf-format-the-body"><span class="header-section-number">9.5.1</span> VCF Format – The Body</a></li>
  <li><a href="#vcf-format-the-header" id="toc-vcf-format-the-header" class="nav-link" data-scroll-target="#vcf-format-the-header"><span class="header-section-number">9.5.2</span> VCF Format – The Header</a></li>
  <li><a href="#boneyard" id="toc-boneyard" class="nav-link" data-scroll-target="#boneyard"><span class="header-section-number">9.5.3</span> Boneyard</a></li>
  </ul></li>
  <li><a href="#segments" id="toc-segments" class="nav-link" data-scroll-target="#segments"><span class="header-section-number">9.6</span> Segments</a></li>
  <li><a href="#conversionextractions-between-different-formats" id="toc-conversionextractions-between-different-formats" class="nav-link" data-scroll-target="#conversionextractions-between-different-formats"><span class="header-section-number">9.7</span> Conversion/Extractions between different formats</a></li>
  <li><a href="#visualization-of-genomic-data" id="toc-visualization-of-genomic-data" class="nav-link" data-scroll-target="#visualization-of-genomic-data"><span class="header-section-number">9.8</span> Visualization of Genomic Data</a>
  <ul class="collapse">
  <li><a href="#sample-data" id="toc-sample-data" class="nav-link" data-scroll-target="#sample-data"><span class="header-section-number">9.8.1</span> Sample Data</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bioinformatic file formats</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Almost all the high-throughput sequencing data you will deal with should arrive in just a few different formats. There are some specialized formats (like those output by the program TASSEL, etc.) but we will largely ignore those, focusing instead on the formats used in production by the 1000 genomes and 10K vertebrate genomes projects. In a sentence, the most important are: FASTA, FASTQ, SAM, BAM, and VCF.</p>
<p>Plan: Go over these, and for each, pay special attention to compressed and indexed forms and explain why that is so important. I think that we should probably talk about the programs that are available for manipulating each of these, as well, but I won’t add that until we all have access to an HPC or other proper Unix environment.</p>
<p>I was originally going to do tools for manipulating files in the different formats, but I will do that in a separate chapter(s) later.</p>
<section id="sequences" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="sequences"><span class="header-section-number">9.1</span> Sequences</h2>
</section>
<section id="fastq" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="fastq"><span class="header-section-number">9.2</span> FASTQ</h2>
<p>The FASTQ format is the standard format for lightly-processed data coming off an Illumina machine. If you are doing whole genome sequencing, it is typical for the Illumina processing pipeline to have separated all the reads with different barcodes into different, separate files. Typically this means that all the reads from one library prep for one sample will be in a single file. The barcodes and any associated additional adapter sequence is typically also removed from the reads. If you are processing RAD data, the reads may not be separated by barcode, because, due to the vagaries of the RAD library prep, the barcodes might appear on different ends of some reads than expected.</p>
<p>A typical file extension for FASTQ files is <code>.fq</code>. Almost all FASTQ files you get from a sequencer should be gzipped to save space. Thus, in order to view the file you will have to uncompress it. Since you would, in most circumstances, want to visually inspect just a few lines, it is best to do that with <code>gzcat</code> and pipe the output to <code>head</code>.</p>
<p>As we have seen, paired-end sequencing produces two separate reads of a DNA fragment. Those two different reads are usually stored in two separate files named in such a manner as to transparently denote whether it contains sequences obtained from read 1 or read 2. For example <code>bird_08_B03_R1.fq.gz</code> and <code>bird_08_B03_R2.fq.gz</code>. Read 1 and Read 2 from a paired read must occupy the sames lines in their respective files, i.e., lines 10001-10004 in <code>bird_08_B03_R1.fq.gz</code> and lines 10001-10004 in <code>bird_08_B03_R2.fq.gz</code> should both pertain to the same DNA fragment that was sequenced. That is what is meant by “paired-end” sequencing: the sequences come in pairs from different ends of the same fragment.</p>
<p>The FASTQ format is <em>very</em> simple: information about each read occupies just four lines. This means that the number of lines in a proper FASTQ file must always be a multiple of four. Briefly, the four lines of information about each read are always in the same order as follows:</p>
<ol type="1">
<li>An Identifier line</li>
<li>The DNA sequence as A’s, C’s, G’s and T’s.</li>
<li>A line that is almost always simply a <code>+</code> sign, but can optionally be followed by a repeat of the ID line.</li>
<li>An ASCII-encoded, Phred-scaled base quality score. This gives an estimated measure of certainty about each base call in the sequence.</li>
</ol>
<p>The code block below shows three reads worth (twelve lines) of information from a FASTQ file. Take a moment to identify the four different lines for each read.</p>
<pre><code>@K00364:64:HTYYCBBXX:1:1108:4635:14133/1
TAGAATACGCCAGGTGTAAGAATAGTAGAATACGCCAGGTGTAAGAATAGTAGAACACGCCAGGTGTAAGAATAGTAGAA
+
AAAFFJJJJJFFJFJJJFJJFFJFJFJJJJJJJJFFJJJFJJJFJJAJJFJJFJJFJJJ7JJJF-&lt;JAFJJ&lt;F&lt;AJAJJF
@K00364:64:HTYYCBBXX:1:1108:5081:25527/1
AAAACACCAAAAGAAAGATGCCCAGGGTCCCTGCTCATCTGCGTGAAAGTGACTTAGGCATGCTGCAAGGAGGCATGAGG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@K00364:64:HTYYCBBXX:1:1108:5852:47295/1
AGGTGGCTCTAGAAGGTTCTCGGACCGAGAAACAGCCTCGTACATTTGCAATGATTTCAATTCATTTTGACCATTACGAA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ</code></pre>
<p>Lines 2 and 3 are self-explanatory, but we will expound upon lines 1 and 4 below.</p>
<section id="illumina-ids" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="illumina-ids"><span class="header-section-number">9.2.1</span> Line 1: Illumina identifier lines</h3>
<p>The identifier line can be just about any string that starts with an <code>@</code>, but, from Illumina data you might see something like this:</p>
<pre><code>@K00364:64:HTYYCBBXX:1:1108:4635:14133/1</code></pre>
<p>The colons (and the <code>/</code>) are field separators. The separate parts of the line above are interpreted something along the lines as follows (keeping in mind that Illumina occasionally changes the format and that there may be additional optional fields):</p>
<pre><code>@           : mandatory character that starts the ID line
K00364      : Unique sequencing machine ID 
64          : Run number on instrument
HTYYCBBXX   : Unique flow cell identifier
1           : Lane number
1108        : Tile number (section of the lane)
4635        : x-coordinate of the cluster within the tile
14133       : y-coordinate of the cluster within the tile
1           : Whether the sequence is from read 1 or read 2 </code></pre>
<p>For Illumina data processed with versions 1.8+ of Casava, the identifier lines are a little different, like this:</p>
<pre><code>@A00600:191:HY75HDSX2:1:2624:27480:35744 2:N:0:AAGACCGT+CAATCGAC</code></pre>
<p>in which we have:</p>
<pre><code>@           : mandatory character that starts the ID line
A00600      : Unique sequencing machine ID 
191         : Run number on instrument
HY75HDSX2   : Unique flow cell identifier
1           : Lane number
2624        : Tile number (section of the lane)
27480       : x-coordinate of the cluster within the tile
35744       : y-coordinate of the cluster within the tile

2                 : Whether the sequence is from read 1 or read 2 
N                 : N if the sequence was not flagged as crappy by the maching, Y otherwise
0                 : 0 when no control bits are turned on
AAGACCGT+CAATCGAC : Index/barcode of the sample</code></pre>
<p>Question: For paired reads, do you expect the x- and y-coordinates for read 1 and read 2 to be the same?</p>
</section>
<section id="bqscores" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="bqscores"><span class="header-section-number">9.2.2</span> Line 4: Base quality scores</h3>
<p>The base quality scores give an estimate of the probability that the base call is incorrect. This comes from data the sequencer collects on the brightness and compactness of the cluster radiance, other factors, and Illumina’s own models for base call accuracy. If we let <span class="math inline">\(p\)</span> be the probability that a base is called incorrectly, then <span class="math inline">\(Q\)</span>, the Phred-scaled base quality score, is:</p>
<p><span class="math display">\[
Q = \lfloor-10\log_{10}p\rfloor,
\]</span> where <span class="math inline">\(\lfloor x \rfloor\)</span> means “the largest integer smaller than <span class="math inline">\(x\)</span>.</p>
<p>To get the estimate of the probability that the base is called incorrectly from the Phred scaled score, you invert the above equation:</p>
<p><span class="math display">\[
p = \frac{1}{10^{Q/10}}
\]</span> Base quality scores from Illumina range from 0 to 40. The easiest values to use as guideposts are <span class="math inline">\(Q = 0, 10, 20, 30, 40\)</span>, which correspond to error probabilites of 1, 1 in 10, 1 in 100, 1 in 1,000, and 1 in 10,000, respectively.</p>
<p>All this is fine and well, but when we look at the quality score line above we see something like <code>7JJJF-&lt;JAFJJ&lt;F&lt;AJAJJF</code>. What gives? Well, from a file storage and parsing perspective, it makes sense to only use a single character to store the quality score for every base. So, that is what has been done: each of those single characters represents a quality score—a number between 0 and 40, inclusive.</p>
<p>The values that have been used are the <em>decimal representations of ASCII text characters</em> minus 33.<br>
The decimal representation or each character can be found in <a href="#fig-ascii">Figure&nbsp;<span>9.1</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ascii" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figs/ascii-crop.png" class="img-fluid figure-img" width="1842"></p>
<figcaption class="figure-caption">Figure&nbsp;9.1: This lovely ASCII table shows the binary, hexadecimal, octal and decimal representations of ASCII characters (in the corners of each square; see the legend rectangle at bottom. Table produced from TeX code written and developed by Victor Eijkhout available at <a href="https://ctan.math.illinois.edu/info/ascii-chart/ascii.tex">https://ctan.math.illinois.edu/info/ascii-chart/ascii.tex</a></figcaption>
</figure>
</div>
</div>
</div>
<p>The decimal representation is in the upper left of each character’s rectangle.</p>
<p>Find the characters corresponding to base quality scores of 0, 10, 20, 30, and 40. Remember that the base quality score is the character’s decimal representation <em>minus 33</em>.</p>
<p>Here is another question: why do you think the scale starts with ASCII character 33?</p>
</section>
</section>
<section id="fasta" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="fasta"><span class="header-section-number">9.3</span> FASTA</h2>
<p>The FASTQ format, described above, is tailored for representing short DNA sequences—and their associated quality scores—that have been generated from high-throughput sequencing machines. A simpler, leaner format is used to represent longer DNA sequences that have typically been established from a lot of sequencing, and which no longer travel with their quality scores. This is the FASTA format, which you will typically see storing the DNA sequence from <em>reference genomes</em>. FASTA files typically use the file extensions <code>.fa</code>, <code>.fasta</code>, or <code>.fna</code>, the latter denoting it as a FASTA file of nucleotides.</p>
<p>In an ideal world, a reference genome would contain a single, uninterrupted sequence of DNA for every chromosome. While the resources for some well-studied species include “chromosomal-level assemblies” which have much sequence organized into chromosomes in a FASTA file, even these genome assemblies often include a large number of short fragments of sequence that are known to belong to the species, but whose location and orientation in the genome remain unknown.</p>
<p>More often, in conservation genetics, the reference genome for an organism you are working on might be the product of a recent, small-scale, assembly of a <em>low-coverage genome</em>. In this case, the genome may be represented by thousands, or tens of thousands, of <em>scaffolds</em>, only a few of which might be longer than one or a few megabases. All of these scaffolds go into the FASTA file of the reference genome.</p>
<p>Here are the first 10 lines of the FASTA holding a reference genome for Chinook salmon:</p>
<pre><code>&gt;CM008994.1 Oncorhynchus tshawytscha isolate JC-2011-M1
AGTGTAGTAGTATCTTACCTATATAGGGGACAGTGTAGTAGTATCTTACTTATTTGGGGGACAATGCTCTAGTGTAGTAG
AATCTTACCTTTATAGGGGACAGTGCTGGAGTGCACTGGTATCTTACCTATATAGGGGACAGTGCTGGAGTGTAGTAGTG
TCTCGGCCCACAGCCGGCAGGCCTCAGTCTTAGTTAGACTCTCCACTCCATAAGAAAGCTGGTACTCCATCTTGGACAGG
ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA
TGTGTGGTACATGTTTACAGAGAAGGAGtatattaaaaacagaaaactgTTTTGGttgaaatatttgtttttgtctgaAG
CCCGAAAAACACATGAAATTCAAAAGATAATTTGACCTACGCACTAACTAGGCTTTTCAGCAGCTCAACTACTGTCCGTT
TATTGATCTACTGTACTGCAACAACATATGTACTCACACAACAGACTATATTGGATTCAGACAGGACCTATAGGTTACCA
TGCTTCCTCTCTACAGGACCTATAGGTTACCATGCTTCCTCTCTACAAGGTCTATAGGTTACCATGCGTCCTCTCTACAG
GACCTATAGGTTACCATGCTTCCTCTCTACAGGGCCTATAGGTTACCATGCTTCCTCTCTACAGGACCTGTAGGTTACCA</code></pre>
<p>The format is straightforward: any line starting with <code>&gt;</code> is interpreted as a line holding the identifier of the following sequence. In this case, the identifier is <code>CM008994.1</code>. The remainder of the line (following the first white space) are further comments about the sequence, but will not typically be carried through downstream analysis (such as aligment) pipelines. In this case <code>CM008994.1</code> is the name of an assembled chromosome in this reference genome. The remaining lines give the DNA sequence of that assembled chromosome.</p>
<p>It is convention with FASTA files that lines of DNA sequence should be less than 80 characters, but this is inconsistently enforced by different analysis programs. However, most of the FASTA files you will see will have lines that are 80 characters long.</p>
<p>In the above fragment, we see DNA sequence that is either upper or lower case. A common convention is that the lowercase bases are segments of DNA that have been inferred (by, for example RepeatMasker) to include repetitive DNA. It is worth noting this if you are trying to design assays from sequence data! However, not all reference genomes have repeat-sequences denoted in this fashion.</p>
<p>Most reference genomes contain gaps. Sometimes the length of these gaps can be accurately known, in which case each missing base pair is replaced by an <code>N</code>. Sometimes gaps of unknown length are represented by a string of <code>N</code>’s of some fixed length (like 100).</p>
<p>Finally, it is worth reiterating that the sequence in a reference-genome FASTA file represents the sequence only one strand of a double-stranded molecule. In chromosomal-scale assemblies there is a convention to use the strand that has its 5’ end at the telomere of the short arm of the chromosome <span class="citation" data-cites="cartwrightMultiplePersonalitiesWatson2011">[@cartwrightMultiplePersonalitiesWatson2011]</span>. Obviously, such a convention cannot be enforced in a low-coverage genome in thousands of pieces. In such a genome, different scaffolds will represent sequence on different strands; however the sequence in the FASTA file, whichever strand it is upon, is taken to be the reference, and that sequence is referred to as the <em>forward</em> strand of the reference genome.</p>
<section id="genomic-ranges" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="genomic-ranges"><span class="header-section-number">9.3.1</span> Genomic ranges</h3>
<p>Almost every aspect of genomics or bioinformatics involves talking about the “address” or “location” of a piece of DNA in the reference genome. These locations within a reference genome can almost universally be described in terms of a “genomic range” with a format that looks like:</p>
<pre><code>SegmentName:start-stop</code></pre>
<p>For example,</p>
<pre><code>CM008994.1:1000001-1001000</code></pre>
<p>denotes the 1 Kb chunk of DNA starting from position 1000001 and proceeding to (and including!) position 1001000. Such nomenclature is often referred to as the <em>genomic coordinates</em> of a segment.</p>
<p>In most applications we will encounter, the first position in a chromosome is labeled 1. This is called a <em>base 1 coordinate system</em>. In some genomic applications, a <em>base 0 coordinate system</em> is employed; however, for the most part such a system is only employed internally in the guts of code of software that we will use, while the user interface of the software consistently uses a base 1 coordinate system.</p>
<p>Sometimes you will have to convert between base 0 and base1 coordinate systems. Thinking about how to do this is easy if you keep a simple picture in your head—I like to think of it as, the base-1 coordinate system counts “beads” that are the actual base pairs, while the base-0 system counts “fences” that separate the beads. In the following picture, the fences and their corresponding numbers are red, while the beads and their corresponding numbers are black.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="figs/base-0-and-1-cropped.svg" class="img-fluid"></p>
</div>
</div>
<p>From this picture, it is pretty clear that if you have a base-1 range from <span class="math inline">\(x\)</span> to <span class="math inline">\(y\)</span> (with <span class="math inline">\(x \leq y\)</span>), then you could refer to that by the base-0 range from <span class="math inline">\(x-1\)</span> to <span class="math inline">\(y\)</span> (those are the “fences” that contain the beads). Likewise, if you have a base-0 range from <span class="math inline">\(v\)</span> to <span class="math inline">\(w\)</span> (with <span class="math inline">\(v&lt;w\)</span>), then the corresponding base-1 range would be from <span class="math inline">\(v+1\)</span> to <span class="math inline">\(w\)</span>, as those are the beads that are contained by the fences at <span class="math inline">\(v\)</span> and <span class="math inline">\(w\)</span>.</p>
</section>
<section id="extracting-genomic-ranges-from-a-fasta-file" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="extracting-genomic-ranges-from-a-fasta-file"><span class="header-section-number">9.3.2</span> Extracting genomic ranges from a FASTA file</h3>
<p>Commonly (for example, when designing primers for assays) it is necessary to pick out a precise genomic range from a reference genome. This is something that you should <em>never</em> try to do by hand. That is too slow and too error prone. Rather the software package <code>samtools</code> (which will be discussed in detail later) provides the <code>faidx</code> utility to <em>index</em> a FASTA file. It then uses that index to provide lightning fast access to specific genomic coordinates, returning them in a new FASTA file with identifiers giving the genomic ranges. Here is an example using <code>samtools faidx</code> to extract four DNA sequences of length 150 from within the Chinook salmon genome excerpted above:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># assume the working directory is where the fasta file resides</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create the index</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="ex">samtools</span> faidx GCA_002831465.1_CHI06_genomic.fna</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># that created the file: GCA_002831465.1_CHI06_genomic.fna.fai</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># which holds four columns that constitute the index</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># now we extract the four sequences:</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="ex">samtools</span> faidx <span class="dt">\</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    GCA_002831465.1_CHI06_genomic.fna <span class="dt">\</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    CM009007.1:3913989-3914138 <span class="dt">\</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    CM009011.1:2392339-2392488 <span class="dt">\</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    CM009013.1:11855194-11855343 <span class="dt">\</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    CM009019.1:1760297-1760446</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co"># the output is like so:</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="op">&gt;</span>CM009007.1:3913989-3914138</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="ex">TTACCGAtggaacattttgaaaaacacaaCAATAAAGCCTTGTGTCCTATTGTTTGTATT</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="ex">TGCTTCGTGCTGTTAATGGTAgttgcacttgattcagcagccgtAGCGCCGGGAAggcag</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="ex">tgttcccattttgaaaaaTGTCATGTCTGA</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="op">&gt;</span>CM009011.1:2392339-2392488</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="ex">gatgcctctagcactgaggatgccttagaccgctgtgccactcgggaggccttcaGCCTA</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a><span class="ex">ACTCTAACTGTAAGTAAATTGTGTGTATTTTTGGGTACATTTCGCTGGTCCCCACAAGGG</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="ex">GAAAGggctattttaggtttagggttaagg</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="op">&gt;</span>CM009013.1:11855194-11855343</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="ex">TGAGGTTTCTGACTTCATTTTCATTCACAGCAGTTACTGTATGCCTCGGTCAAATTGAAA</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="ex">GGAAAGTAAAGTAACCATGTGGAGCTGtatggtgtactgtactgtactgtattgtactgt</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="ex">attgtgtgGGACGTGAGGCAGGTCCAGATA</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="op">&gt;</span>CM009019.1:1760297-1760446</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="ex">ttcccagaatctctatgttaaccaaggtgtttgcaaatgtaacatcagtaggggagagag</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="ex">aggaaataaagggggaagaggtatttatgactgtcataaacctacccctcaggccaacgt</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a><span class="ex">catgacactcccgttaatcacacagactGG</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="downloading-reference-genomes-from-ncbi" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="downloading-reference-genomes-from-ncbi"><span class="header-section-number">9.3.3</span> Downloading reference genomes from NCBI</h3>
<p>I might want to write blurb here about how much nicer I find it is to use the ftp link: <a href="http://ftp.ncbi.nlm.nih.gov/genomes/genbank/">http://ftp.ncbi.nlm.nih.gov/genomes/genbank/</a> to find genomes on Genbank. Although now that the number of genomes is growing so quickly, it can take quite a while for the pages to load. But I still find it easier to navigate to exactly the files I want using this system than the actual user interface that they have.</p>
</section>
</section>
<section id="sambamfiles" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="sambamfiles"><span class="header-section-number">9.4</span> Alignments</h2>
<p>A major task in bioinformatics is <em>aligning</em> reads from a sequencing machine to a reference genome. We will discuss the operational features of that task in a later chapter, but here we treat the topic of the SAM, or Sequence Alignment Map, file format which is widely used to represent the results of sequence alignment. We attempt to motivate this topic by first considering a handful of the intricacies that arise during sequence alignment, before proceeding to a discussion of the various parts of the SAM file that are employed to handle the many and complex ways in which DNA alignments can occur and be represented. This will necessarily be an incomplete and relatively humane introduction to SAM files. For the adventurous a more complete—albeit astonishingly terse—description of the <a href="https://samtools.github.io/hts-specs/SAMv1.pdf">SAM format specification</a> is maintained and regularly updated.</p>
<section id="how-might-i-align-to-thee-let-me-count-the-ways" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="how-might-i-align-to-thee-let-me-count-the-ways"><span class="header-section-number">9.4.1</span> How might I align to thee? Let me count the ways…</h3>
<p>We are going to consider the alignment of very short (10 bp) paired-end reads from the ends of a short (50 bp) fragment from the fourth line of the FASTA file printed above. In other words, those 80 bp of the reference genome are:</p>
<pre><code>5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'</code></pre>
<p>And we will be considering double-stranded DNA occupying the middle 50 base pairs of that piece of reference genome. That piece of double stranded DNA looks like:</p>
<pre><code>5'  ACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGA  3'
    ||||||||||||||||||||||||||||||||||||||||||||||||||
3'  TGGACGTCCTGTGTGTGCGTCCAAATGATTCCCAAATGAGTTGTGTCACT  5'</code></pre>
<p>If we print it alongside (underneath, really) our reference genome, we can see where it lines up:</p>
<pre><code>5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'
               5'  ACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGA  3'
                   ||||||||||||||||||||||||||||||||||||||||||||||||||
               3'  TGGACGTCCTGTGTGTGCGTCCAAATGATTCCCAAATGAGTTGTGTCACT  5'</code></pre>
<p>Now, remember that any template being sequenced on an Illumina machine is going to be single-stranded, and we have no control over which strand, from a double-stranded fragment of DNA, will get sequenced. Futhermore, recall that for this tiny example, we are assuming that the reads are only 10 bp long. Ergo, if everything has gone according to plan, we can expect to see two different possible <em>templates</em>, where I have denoted the base pairs that do not get sequenced with <code>-</code>’s</p>
<pre><code>either:
               5'  ACCTGCAGGA------------------------------AACACAGTGA  3'
or:
               3'  TGGACGTCCT------------------------------TTGTGTCACT  5'</code></pre>
<p>If we see the top situation, we have a situation in which the template that reached the lawn on the Illumina machine comes from the strand that is represented in the reference genome. This is called the <em>forward strand</em>. On the other hand, the bottom situation is one in which the template is from the reverse complement of the strand represented by the reference. This is called the <em>reverse strand</em>.</p>
<p>Now, things start to get a little more interesting, because we don’t get to look at the the entire template as one contiguous piece of DNA in the 5’ to 3’ direction. Rather, we get to “see” one end of it by reading Read 1 in the 5’ to 3’ direction, and then we “see” the other end of it by reading Read 2, also in the 5’ to 3’ direction, <em>but Read 2 is read off the complementary strand</em>.</p>
<p>So, if we take the template from the top situation:</p>
<pre><code>the original template is:
               5'  ACCTGCAGGA------------------------------AACACAGTGA  3'
               
So the resulting reads are:

Read 1:        5'  ACCTGCAGGA  3'   --&gt; from 5' to 3' on the template
Read 2:        5'  TCACTGTGTT  3'   --&gt; the reverse complement of the
                                        read on the 3' end of the template</code></pre>
<p>And if we take the template from the bottom scenario:</p>
<pre><code>the original template is:
               3'  TGGACGTCCT------------------------------TTGTGTCACT  5'
               
So the resulting reads are:

Read 1:        5'  TCACTGTGTT  3'   --&gt; from 5' to 3' on the template
Read 2:        5'  ACCTGCAGGA  3'   --&gt; the reverse complement of the
                                        read on the 3' end of the template</code></pre>
<p>Aha! Regardless of which strand of DNA the original template comes from, sequences must be read off of it in a 5’ to 3’ direction (as that is how the biochemistry works). So, there are only two possible sequences you will see, and these correspond to reads from 5’ to 3’ off of each strand. So, the only difference that happens when the template is from the forward or the reverse strand (relative to the reference), is whether Read 1 is from the forward strand and Read 2 is from the reverse strand, or whether Read 1 is from the reverse strand and Read 2 is from the forward strand. The actual pair of sequences you will end up seeing is still the same.</p>
<p>So, to repeat, with a segment of DNA that is a faithful copy of the reference genome, there are only two read sequences that you might see, and as we will show below <em>Read 1 and Read 2 must align to opposite strands of the reference.</em></p>
<p>What does a faithful segment from the reference genome look like in alignment? Well, in the top case we have:</p>
<pre><code>      Read 1:  5'  ACCTGCAGGA  3' 
5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'
forward-strand
    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
reverse-strand
3'  TGTATCTGTCCCTGGTGGACGTCCTGTGTGTGCGTCCAAATGATTCCCAAATGAGTTGTGTCACTTGTCGTATATGGTCT  5'  
                                              Read 2:  3'  TTGTGTCACT  5'</code></pre>
<p>And in the bottom case we have:</p>
<pre><code>      Read 2:  5'  ACCTGCAGGA  3' 
5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'  
forward-strand
    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
reverse-strand
3'  TGTATCTGTCCCTGGTGGACGTCCTGTGTGTGCGTCCAAATGATTCCCAAATGAGTTGTGTCACTTGTCGTATATGGTCT  5'
                                              Read 1:  3'  TTGTGTCACT  5'</code></pre>
<p>Note that, although one of the reads always aligns to the reverse strand, the position at which it is deemed to align is still read off of the position on the forward strand. (Thank goodness for that! Just think how atrocious it would be if we counted positions of fragments mapping to the reverse strand by starting from the reverse strands’s 5’ end, on the other end of the chromosome, and counting forward from there!!)</p>
<p>Note that the <em>alignment position</em> is one of the most important pieces of information about an alignment. It gets recorded in the <strong>POS</strong> column of an alignment. It is recorded as the first position (counting from 1 on the 5’ end of the forward reference strand) at which the alignment starts. Of course, the name of the reference sequence the read maps to is essential. In a SAM file this is called the <strong>RNAME</strong> or reference name.</p>
<p>Both of the last two alignments illustrated above involve paired end reads that align “properly,” because one read in the pair aligns to the forward strand and one read aligns to the reverse strand of the reference genome. As we saw above, that is just what we would expect if the template we were sequencing is a faithful copy (apart from a few SNPs or indels) of either the forward or the reverse strand of the reference sequence. In alignment parlance we say that each of the reads is “mapped in a proper pair.” This is obviously an important piece of information about an alignment and it is recorded in a SAM file in the so-called <strong>FLAG</strong> column for each alignment. (More on these flags later…)</p>
<p>How can a read pair not be properly mapped? There are a few possibilities:</p>
<ol class="example" type="1">
<li>One read of the pair gets aligned, but the other does not. For example something that in our schematic would look like this:</li>
</ol>
<pre><code>5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'
               5'  ACCTGCAGGA  3'</code></pre>
<ol start="2" class="example" type="1">
<li>Both reads of the pair map to the same strand. If our paired end reads looked like:</li>
</ol>
<pre><code>Read 1:   5'  ACCTGCAGGA  3'
Read 2:   5'  AACACAGTGA  5'</code></pre>
<p>then they would both align nicely to just the forward strand of the reference genome:</p>
<pre><code>5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'
               5'  ACCTGCAGGA------------------------------AACACAGTGA  3'</code></pre>
<p>And, as we saw above, this would indicate that the template must not conform to the reference genome in some way. This may occur if there is a rearrangement (like an inversion, etc.) in the genome being sequenced, relative to the reference genome.</p>
<ol start="3" class="example" type="1">
<li>The two different reads of a pair get aligned to different chromosomes/scaffolds or they get aligned so far apart on the same chromosome/scaffold that the alignment program determines the pair to be aberrant. This evaluation requires that the program have a lot of other paired end reads from which to estimate the distribution, in the sequencing library, of the <em>template length</em>—the length of the original template. The template length for each read pair is calculated from the mapping positions of the two reads and is stored in the <strong>TLEN</strong> column of the SAM file.</li>
</ol>
<p>What is another way I might align to thee? Well, one possbility is that a read pair might align to many different places in the genome (this can happen if the reads are from a repetitive element in the genome, for example). In such cases, there is typically a “best” or “most likely” alignment, which is called the <em>primary alignment</em>. The SAM file output might record other “less good” alignments, which are called <em>secondary alignments</em> and whose status as such is recorded in the <strong>FLAG</strong> column. The aligner <code>bwa mem</code> has an option to allow you to output all secondary alignments. Since you don’t typically output and inspect all secondary alignments (something that would be an unbearable task), most aligners provide some measure of confidence about the alignment of a read pair. The aligner, <em>bwa</em>, for example, looks at all possible alignments and computes a score for each. Then it evaluates confidence in the primary alignment by comparing its score to the sum of the scores of all the alignments. This provides the <em>mapping quality score</em> found in the <strong>MAPQ</strong> column of a SAM file. It can be interpreted, roughly, as the probability that the given alignment of the read pair is incorrect. These can be small probabilities, and are represented as Phred scaled values (using integers, not characters!) in the SAM file.</p>
<p>The last way that a read might align to a reference is by not perfectly matching every base pair in the reference. Perhaps only the first part of the read matches base pairs in the reference, or maybe the read contains an insertion or a deletion. For example, if instead of appearing like <code>5'  ACCTGCAGGA  3'</code>, one of our reads had an insertion of AGA, giving: <code>5'  ACCAGAGTGCAGGA  3'</code>, this fragment would still align to the reference, at 10 bp, and we might record that alignment, but would still want a compact way of denoting the position and length of the insertion—a task handled by the <strong>CIGAR</strong> column.</p>
<p>To express all these different ways in which an alignment can occur, each read occupies a single line in a SAM file. This row holds information about the read’s alignment to the reference genome in a number of TAB-delimited columns. There are 11 required columns in each alignment row, after which different aligners may provide additional columns of information. <a href="#tbl-sam-cols">Table&nbsp;<span>9.1</span></a> gives a brief description of the 11 required columns (intimations of most of which occurred in <strong>ALL CAPS BOLDFACE</strong> in the preceding paragraphs. Some, like <strong>POS</strong> are relatively self-explanatory. Others, like <strong>FLAG</strong> and <strong>CIGAR</strong> benefit from further explanation as given in the subsections below.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-sam-cols" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;9.1: Brief description of the 11 required columns in a SAM file.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Column</th>
<th style="text-align: left;">Field</th>
<th style="text-align: left;">Data Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">QNAME</td>
<td style="text-align: left;">String</td>
<td style="text-align: left;">Name/ID of the read (from FASTQ file)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">FLAG</td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">The SAM flag</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">RNAME</td>
<td style="text-align: left;">String</td>
<td style="text-align: left;">Name of scaffold/chromosome the read aligns to</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">POS</td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">1-based 5’-most alignment position on reference forward strand</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">MAPQ</td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">Phred-scaled mapping quality score</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">CIGAR</td>
<td style="text-align: left;">String</td>
<td style="text-align: left;">String indicating matches, indels and clipping in alignment</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">RNEXT</td>
<td style="text-align: left;">String</td>
<td style="text-align: left;">Scaffold/chromosome that the read’s mate aligns to</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">PNEXT</td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">Alignment position of the read’s mate</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">TLEN</td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">Length of DNA template whose ends were read (in paired-end sequencing)</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">SEQ</td>
<td style="text-align: left;">String</td>
<td style="text-align: left;">The sequence of the read, represented in 5’ to 3’ on the reference forward strand</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">QUAL</td>
<td style="text-align: left;">String</td>
<td style="text-align: left;">Base quality scores, ordered from 5’ to 3’ on the reference forward strand</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="play-with-simple-alignments" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="play-with-simple-alignments"><span class="header-section-number">9.4.2</span> Play with simple alignments</h3>
<p>Team up with someone who has a Mac. They can clone the RStudio project repository on GitHub at <a href="https://github.com/eriqande/alignment-play">https://github.com/eriqande/alignment-play</a> (by opening a new RStudio project with the “From Version Control” –&gt; GitHub option, for example).</p>
<p>This has a notebook that will let us do simple alignments and familiarize ourselves with the output in SAM format. This is only available on Mac because <code>bwa</code> and <code>samtools</code> are not available on conda compiled for windows (and because I figured there wouldn’t be many folks running Linux on their laptops).</p>
<p>Read through the R notebook and run the code. See how the SAM flags and or the CIGAR strings change when you make read1 and read2 different sequences, as shown in the notebook.</p>
</section>
<section id="sam-flags" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="sam-flags"><span class="header-section-number">9.4.3</span> SAM Flags</h3>
<p>The FLAG column expresses the status of the alignment associated with a given read (and its <em>mate</em> in paired-end sequencing) in terms of a combination of 12 yes-or-no statements. The combination of all of these “yesses” and “nos” for a given aligned read is called its SAM <em>flag</em>. The yes-or-no status of any single one of the twelve statements is called a “bit” because it can be thought of as a single binary digit whose value can be 0 (No/False) or 1 (Yes/True). Sometimes a picture can be helpful: we can represent each statement as a circle which is shaded if it is true and open if it is false. Thus, if all 12 statements are false you would see <span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}\)</span>. However, if statements 1, 2, 5, and 7 are true then you would see <span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\bullet}{\circ}{\bullet}~{\circ}{\circ}{\bullet}{\bullet}\)</span>. In computer parlance we would say that bits 1, 3, 5, and 7 are “set” if they indicate Yes/True. As these are bits in a binary number, each bit is associated with a power of 2 as shown in <a href="#tbl-sam-flags">Table&nbsp;<span>9.2</span></a>, which also lists the meaning of each bit.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-sam-flags" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;9.2: SAM flag bits in a nutshell. The description of these in the SAM specification is more general, but if we restrict ourselves to paired-end Illumina data, each bit can be interpreted by the meanings shown here. The “bit-grams” show a visual representation of each bit with open circles meaning 0 or False and filled circles denoting 1 or True. The bit grams are broken into three groups of four, which show the values that correspond to different place-columns in the hexadecimal representation of the bit masks.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">bit-#</th>
<th style="text-align: left;">bit-gram</th>
<th style="text-align: left;"><span class="math inline">\(2^x\)</span></th>
<th style="text-align: left;">dec</th>
<th style="text-align: left;">hex</th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\bullet}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^0\)</span></td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0x1</td>
<td style="text-align: left;">the read is paired (i.e.&nbsp;comes from paired-end sequencing.)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\bullet}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^1\)</span></td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">0x2</td>
<td style="text-align: left;">the read is mapped in a proper pair</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}~{\circ}{\bullet}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^2\)</span></td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">0x4</td>
<td style="text-align: left;">the read is not mapped/aligned</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}~{\bullet}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^3\)</span></td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">0x8</td>
<td style="text-align: left;">the read’s mate is not mapped/aligned</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\bullet}~{\circ}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^4\)</span></td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">0x10</td>
<td style="text-align: left;">the read maps to the reverse strand</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\bullet}{\circ}~{\circ}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^5\)</span></td>
<td style="text-align: left;">32</td>
<td style="text-align: left;">0x20</td>
<td style="text-align: left;">the read’s mate maps to the reverse strand</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\circ}{\bullet}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^6\)</span></td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">0x40</td>
<td style="text-align: left;">the read is read 1</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\circ}~{\bullet}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^7\)</span></td>
<td style="text-align: left;">128</td>
<td style="text-align: left;">0x80</td>
<td style="text-align: left;">the read is read 2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\circ}{\bullet}~{\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^8\)</span></td>
<td style="text-align: left;">256</td>
<td style="text-align: left;">0x100</td>
<td style="text-align: left;">the alignment is not primary (don’t use it!)</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\circ}{\bullet}{\circ}~{\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^9\)</span></td>
<td style="text-align: left;">512</td>
<td style="text-align: left;">0x200</td>
<td style="text-align: left;">the read did not pass platform quality checks</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;"><span class="math inline">\({\circ}{\bullet}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^{10}\)</span></td>
<td style="text-align: left;">1024</td>
<td style="text-align: left;">0x400</td>
<td style="text-align: left;">the read is a PCR (or optical) duplicate</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;"><span class="math inline">\({\bullet}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}~{\circ}{\circ}{\circ}{\circ}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(2^{11}\)</span></td>
<td style="text-align: left;">2048</td>
<td style="text-align: left;">0x800</td>
<td style="text-align: left;">the alignment is part of a chimeric alignment</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>If we think of the 12 bits as coming in three groups of four we can easily represent them as hexadecimal numbers. Hexadecimal numbers are numbers in base-16. They are expressed with a leading “0x” but otherwise behave like decimal numbers, except that instead of a 1’s place, 10’s place, and 100’s place, and so on, we have a 1’s place, a 16’s place, and 256’s place, and so forth. In the first group of four bits (reading from right to left) the bits correspond to 0x1, 0x2, 0x4, and 0x8, in hexadecimal. The next set of four bits correspond to 0x10, 0x20, 0x40, and 0x80, and the last set of four bits correspond to 0x100, 0x200, 0x400, 0x800. It can be worthwhile becoming comfortable with these hexadecimal names of each bit.</p>
<p>In the SAM format, the <strong>FLAG</strong> field records the decimal (integer) equivalent of the binary number that represents the yes-or-no answers to the 12 different statements. It is relatively easy to do arithmetic with the hexadecimal flags to find the decimal equivalent: add up the numbers in each of the three hexadecimal value places (the 1’s, 16’s, and 256’s places) and multiply the result by 16 raised to the number of zeros right of the “x” in the hexadecimal number. For example if the bits set on an alignment are 0x1 &amp; 0x2 &amp; 0x10 &amp; 0x40, then they sum column-wise to 0x3, and 0x50, so the value listed in the FLAG field of a SAM file would be <span class="math inline">\(3 + 5 \cdot 16 = 83\)</span>.</p>
<p>While it is probably possible to get good at computing these 12-bit combinations from hexadecimal in your head, it is also quite convenient to use the Broad Institute’s wonderful <a href="https://broadinstitute.github.io/picard/explain-flags.html">SAM flag calculator</a>.</p>
<p>We will leave our discussion of the various SAM flag values by noting that the large SAM-flag bits (0x100, 0x200, 0x400, and 0x800) all signify something “not good” about the alignment. The same goes for 0x4 and 0x8. On the other hand, when you are dealing with paired-end data, one of the reads has to be read 1 and the other read 2, and that is known from their read names and the FASTQ file that they are in. So, we expect that 0x40 and 0x80 should always be set, trivially. With paired-end data, we are always comforted to see bits 0x1 and 0x2 set, as departures from that condition indicate that the pairing of the read alignments does not make sense given the sequence in the reference genome. As we saw in our discussion of how a template can properly map to a reference, you should be able to convince yourself that, in a properly mapped alignment, exactly one of the two bits 0x10 and 0x20 should be set for one read in the pair, and the other should be set for the other. Therefore, in good, happy, properly paired reads, from a typical whole genome sequencing library preparation, we should find either:</p>
<pre><code>read 1 : 0x1 &amp; 0x2 &amp; 0x10 &amp; 0x40 = 83
read 2 : 0x1 &amp; 0x2 &amp; 0x20 &amp; 0x80 = 163</code></pre>
<p>or</p>
<pre><code>read 1 : 0x1 &amp; 0x2 &amp; 0x20 &amp; 0x40 = 99
read 2 : 0x1 &amp; 0x2 &amp; 0x10 &amp; 0x80 = 147</code></pre>
<p>So, now that we know all about SAM flags and the values that they take, what should we do with them? First, investigating the distribution of SAM flags is an important way of assessing the nature and reliability of the alignments you have made (this is what <em>samtools flagstat</em> is for, as discussed in a later chapter). Second, you might wonder if you should do some sort of filtering of your alignments before you do variant calling. With most modern variant callers, the answer to that is, “No.” Modern variant callers take account of the information in the SAM flags to weight information from different alignments, so, leaving bad alignments in your SAM file should not have a large effect on the final results. Furthermore, filtering out your data might make it hard to follow up on interesting patterns in your data, for example, the occurrence of improperly aligning reads can be used to infer the presence of inversions. If all those improperly paired reads had been discarded, they could not be used in such an endeavor.</p>
<p>Nonetheless, you will want to <em>mark</em> (rather than remove) some aberrations, like PCR duplicates. We discuss that in a later section.</p>
</section>
<section id="cigar" class="level3" data-number="9.4.4">
<h3 data-number="9.4.4" class="anchored" data-anchor-id="cigar"><span class="header-section-number">9.4.4</span> The CIGAR string</h3>
<p><strong>CIGAR</strong> is an acronym for Compressed Idiosyncratic Gapped Alignment Report. It provides a space-economical way of describing the manner in which a single read aligns to a reference genome. It is particularly important for recording the presence of insertions or deletions within the read, relative to the reference genome. This is done by counting up, along the alignment, the number of base pairs that: <em>match</em> (<code>M</code>) the reference; that are <em>inserted</em> (<code>I</code>) into the read and absent from the reference; and that are <em>deleted</em> (<code>D</code>) from the read, but present in the reference. To arrive at the syntax of the CIGAR string you catenate a series of Number-Letter pairs that describe the sequence of matches, insertions and deletions that describe an alignment.</p>
<p>Some examples are in order. We return to our 80 base-pair reference from above and consider the alignment to it of a 10 bp read that looks like <code>5'  ACCTGCAGGA  3'</code>:</p>
<pre><code>5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'
               5'  ACCTGCAGGA  3'</code></pre>
<p>Such an alignment has no insertions or deletions, or other weird things, going on. So its CIGAR string would be <code>10M</code>, signifying 10 matching base pairs. A <em>very important</em> thing to note about this is that the <code>M</code> refers to bases that match in <em>position</em> in the alignment <em>even though they might not match the specific nucleotide types</em>. For example, even if bases 3 and 5 in the read don’t match the exact base nucleotides in the alignment, like this:</p>
<pre><code>5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'
               5'  ACTTACAGGA  3'</code></pre>
<p>its CIGAR string will typically still be <code>10M</code>. (The SAM format allows for an <code>X</code> to denote mismatches in the base nucleotides between a reference and a read, but I have never seen it used in practice.)</p>
<p>Now, on the other hand, if our read carried a deletion of bases 3 and 4. It would look like <code>5'  ACGCAGGA  3'</code> and we might represent it in an alignment like:</p>
<pre><code>5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'
               5'  AC--GCAGGA  3'</code></pre>
<p>where the <code>-</code>’s have replaced the two deleted bases. The CIGAR string for this alignment would be <code>2M2D6M</code>.</p>
<p>Continuing to add onto this example, suppose that not only have bases 3 and 4 been deleted, but also a four-base insertion of <code>ACGT</code> occurs in the read between positions 8 and 9 (of the original read). That would appear like:</p>
<pre><code>5'  ACATAGACAGGGACCACCTGCAG----GACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'
               5'  AC--GCAGACGTGA  3'</code></pre>
<p>where <code>-</code>’s have been added to the reference at the position of the insertion in the read. The CIGAR string for this arrangement would be <code>2M2D4M4I2M</code> which can be hard to parse, visually, if your eyes are getting as old as mine, but it translates to:</p>
<pre><code>2 bp Match  
2 bp Deletion  
4 bp Match  
4 bp Insert   
2 bp Match   </code></pre>
<p>In addition to <code>M</code>, <code>D</code> and <code>I</code> (and <code>X</code>) there are also <code>S</code> and <code>H</code>, which are typically seen with longer sequences. They refer to <em>soft-</em> and <em>hard-clipping</em>, respectively, which are situations in which a terminal piece of the read, from either near the 3’ or 5’ end, does not align to the reference, but the central part, or the other end of the read does. Hard clipping removes the clipped sequence from the read as represented in the SEQ column, while soft clipping does not remove the clipped sequence from the SEQ column representation.</p>
<p>One important thing to understand about CIGAR strings is that they always represent the alignment as it appears in the 5’ to 3’ direction. As a consequence, it is the same whether you are reading it off the read in the 5’ to 3’ direction <em>or</em> if you are reading it off from how the reverse complement of the read would align to the opposite strand of the reference. Another picture is in order: if we saw a situation like the following, with a deletion in Read 1 (which aligns to the reverse strand), the CIGAR string would be, from 5’ to 3’ on Read 1, <code>6M2D2M</code>, which is just what we would have if we were to align the reverse complement of Read 1, called <code>Comp R1</code> below to the forward strand of the reference.</p>
<pre><code>      Read 2:  5'  ACCTGCAGGA  3'            Comp R1:  5'  AA--CAGTGA  3'
5'  ACATAGACAGGGACCACCTGCAGGACACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'  
forward-strand
    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
reverse-strand
3'  TGTATCTGTCCCTGGTGGACGTCCTGTGTGTGCGTCCAAATGATTCCCAAATGAGTTGTGTCACTTGTCGTATATGGTCT  5'
                                              Read 1:  3'  TT--GTCACT  5'</code></pre>
<p>For the most part, it is important to have an understanding of CIGAR strings, though you will rarely end up parsing and using them yourself. That job is best left for the specialized tools that process SAM files and their compressed equivalents, BAM files. Nonetheless, it is worth pointing out that if you want to identify the nucleotide values (i.e.&nbsp;alleles) at different variant positions upon single reads, it is necessary to contend with CIGAR strings to do so. This is one of the things that gets taken care of (with some Perl code) in the R package <a href="https://cran.r-project.org/web/packages/microhaplot/index.html">microhaplot</a> for extracting microhaplotypes from short read data (and then visualizing them).</p>
</section>
<section id="the-seq-and-qual-columns" class="level3" data-number="9.4.5">
<h3 data-number="9.4.5" class="anchored" data-anchor-id="the-seq-and-qual-columns"><span class="header-section-number">9.4.5</span> The SEQ and QUAL columns</h3>
<p>These columns hold the actual reads and quality scores that came off the sequencing machine and were in the FASTQ files. (Note, if you thought that after aligning your reads, the SAM or BAM files would end up taking up less space then the ridiculously large, gzipped FASTQ files you just downloaded from the sequencing center, guess again! SAM files actually have all the information present in a FASTQ, along with extra information about the alignments.)</p>
<p>The only thing that is tricky about these columns is that, if the read aligns to the reverse strand of the reference genome, the entry in the <strong>SEQ</strong> column is the reverse complement of the read that actually appeared in the FASTQ file. Of course, when you read off the letters of DNA from a reverse complement, going left to right the way you read a book, the order in which you encounter the complement of each base from the original sequence is reversed from the way you would read the bases in the original sequence. Accordingly, the order of the base quality scores that appear in the <strong>QUAL</strong> column will be in reverse order is the mapping was to the reverse strand.</p>
</section>
<section id="sam-headers" class="level3" data-number="9.4.6">
<h3 data-number="9.4.6" class="anchored" data-anchor-id="sam-headers"><span class="header-section-number">9.4.6</span> SAM File Headers</h3>
<p>This next section uses an example file that is in the repository at <code>example-files/s001---1.sam</code>. To get it, you might need to sync your fork of the repo and then pull down changes into your main branch.</p>
<p>To this point, we have talked almost exclusively about the rows in a SAM file which record the alignments of different reads. However, if you look at a SAM file (with <code>cat</code> or <code>less</code>, or in a text editor) the first thing you will see is the SAM file <em>header</em>: a series of lines that all start with the <code>@</code> symbol followed by two capital letters. Like <code>@SQ</code>.</p>
<p>Try this:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">less</span> <span class="at">-S</span> example-files/s001---1.sam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Keep hitting the space bar until you get down to the alignments, then use the up-arrow key to go back up through the file and inspect all the header lines.</p>
<p>These file header lines can appear daunting at first, and, when merging or dividing SAM and BAM files can prove to the bane of your existence, so understanding both their purpose and structure is paramount to avoiding some pain down the road.</p>
<p>In a nutshell, the lines in the header provide information to programs (and people) that will be processing the data in a SAM (or BAM, see below) file. Some of the header lines give information about the reference genome that the reads were aligned to, others provide an overview of the various samples (and other information) included in the file, while still others give information about the program and data that produced the SAM file.</p>
<p>If you have ever looked at the SAM header for an alignment to a reference genome that is in thousands of pieces, you were likely overwhelmed by thousands of lines that started with <code>@SQ</code>. Each of these lines gives information about the names and lengths (and optionally, some other information) of sequences that were used as the reference for the alignment.</p>
<p>Each header line begins with an <code>@</code> followed by two capital letters, for example, <code>@RG</code> or <code>@SQ</code>. The two-letter code indicates what kind of header line it is. There are only five kinds of header lines:</p>
<ul>
<li><code>@HD</code>: the “main” header line, which, if present, will be the first line of the file. It’s purpose is to reveal the version of the SAM format in use, and also information about how the alignments in the file are sorted. (You won’t find this line in <code>results/sam/s001---1sam</code>. It’s not there! But we will see it later after converting it to a BAM file and sorting it!)</li>
<li><code>@SQ</code>: typically the most abundant SAM header lines, each of these gives information about a sequence in the reference genome aligned to.</li>
<li><code>@RG</code>: these indicate information about <em>read groups</em>, which are collections of reads that, for the purposes of downstream analysis can all be assumed to be from the same individual and to have been treated the same way during the processes of library preparation and sequencing. We will discuss read groups more fully in the section on alignment.</li>
<li><code>@PG</code>: a line that tells about the program that was used to produced the SAM file.</li>
<li><code>@CO</code>: a line in which a comment can be placed.</li>
</ul>
<p>Look though the header for <code>example-files/s001---1.sam</code> and find the <code>@RG</code> and <code>@PG</code> lines.</p>
<p>Those first three characters (i.e.&nbsp;<code>@</code> followed to two uppercase letters) signify that a line is a header line, but, within each header line, how is information conveyed? In all cases (except for the comment lines using <code>@CO</code>), information within a header line is provided in TAB-delimited, colon-separated <em>key-value</em> pairs. This means that the type or meaning of each piece of information is tagged with a key, like <code>ID</code>, and its <em>value</em> follows that key after a colon. For example, the line</p>
<pre><code>@PG     ID:bwa  PN:bwa  VN:0.7.17-r1188 CL:bwa mem -R @RG\tID:s001_T199967_Lib-1_HY75HDSX2_1_AAGACCGT+CAATCGAC\tSM:T199967\tPL:ILLUMINA\tL
B:Lib-1\tPU:HY75HDSX2.1.AAGACCGT+CAATCGAC resources/genome.fasta results/trimmed/s001---1_R1.fq.gz results/trimmed/s001---1_R2.fq.gz</code></pre>
<p>tells us that the ID of the program that produced the SAM file was <code>bwa</code>, and its version number (VN) was <code>0.7.17-r1188</code>. And it also shows the complete command line (CL) that was used to produce it.</p>
<p>The keys in the key-value pairs are always two uppercase letters. And different keys are allowed (and in some case required) in the context of each of the five different kinds of SAM header lines.</p>
<p>The most important keys for the different kinds of header lines are as follows:</p>
<ul>
<li>For <code>@HD</code>
<ul>
<li><code>VN</code>: the version of the SAM specification in use. This is required.</li>
<li><code>SO</code>: the sort order of the file. The default value is <code>unknown</code>. More commonly, when your SAM/BAM file is prepared for variant calling, it will have been sorted in the order of the reference genome, which is denoted as <code>SO:coordinate</code>. For other purposes, it is important to sort the file in the order of read names, or <code>SO:queryname</code>. It is important to note that setting these values in a SAM file does not sort it. Rather, when you have asked a program to sort a SAM/BAM file, that program will make a note in the header about how it is sorted.</li>
</ul></li>
<li>For <code>@SQ</code>
<ul>
<li><code>SN</code> is the key for the sequence name and is required.<br>
</li>
<li><code>LN</code> is the key for the length (in nucleotide bases) of the sequence, and is also required.</li>
</ul></li>
<li>For <code>@RG</code>
<ul>
<li><code>ID</code> is the only required key for <code>@RG</code> lines. HUGE NOTE: if multiple <code>@RG</code> lines occur in the file, each of their <code>ID</code> values must be different.</li>
<li><code>SM</code> is the key for the name of the sample from which the reads came from. This is the name used when recording genotypes of individuals when doing variant calling.</li>
<li><code>LB</code> denotes the particularl library in which the sample was prepared for sequencing.</li>
<li><code>PU</code> denotes the “Platform Unit,” of sequencing. Typically interpreted to mean the flow-cell and the lane upon which the sample was sequenced. We will talk much more about the contents of read-group header lines, and how to fill them.</li>
<li><code>PL</code> denotes the sequencing technology (PL is short for “platform”) used. If the reads are from an Illumina sequencer, the value would be <code>ILLUMINA</code>.</li>
</ul></li>
<li>For <code>@PG</code>
<ul>
<li><code>ID</code> is required and provides information about the program that produced the SAM output.</li>
<li><code>VN</code> as we saw before, this key lets you record the version of the program used to produce the SAM output.</li>
</ul></li>
</ul>
<p>A complete accounting of the different possible SAM header lines and their contents is given in the <a href="https://samtools.github.io/hts-specs/SAMv1.pdf">SAM specification</a>. It is given in a terse table that is quite informative and is not terribly tough sledding. It is recommended that you read the section on header lines.</p>
</section>
<section id="the-bam-format" class="level3" data-number="9.4.7">
<h3 data-number="9.4.7" class="anchored" data-anchor-id="the-bam-format"><span class="header-section-number">9.4.7</span> The BAM format</h3>
<p>As you might have inferred from the foregoing, SAM files can end up being enormous text files. For our example file, try this: <code>du -h example-files/s001---1.sam</code> to see how big it is:</p>
<p>The two big problems with having such large files are:</p>
<ol type="1">
<li>They could take up a lot of hard drive space.</li>
<li>It would take you (or some program that was processing a SAM file) a lot of time to “scroll” through the file to find any particular alignment you (it) might be interested in.</li>
</ol>
<p>The originators of the SAM format dealt with this by also specifying and creating a compressed <em>binary</em> (meaning “not composed of text”) format to store all the information in a SAM file. This is called a BAM (Binary Alignment Map) file. In a BAM file, each column of information is stored in its native data type (i.e., the way a computer would represent it internally if it were working on it) and then the file holding all of these “rows” is compressed into a series of small blocks in such a way that the file can be indexed, allowing rapid access (without “scrolling” through the whole file) to the alignments within a desired genomic range. As we will see in a later chapter, in order to index such a file for rapid access to alignments in a particular genomic range, the alignments must be sorted in the order of genomic coordinates in the reference sequence.</p>
<p>Since BAM files are smaller than SAM files, and access into them is faster than for SAM files, you will almost always convert your SAM files to BAM files to prepare for futher bioinformatic processing. The main tool used for this purpose is the program <code>samtools</code> (written by the creators of the SAM and BAM formats) for that purpose. We will encounter <code>samtools</code> in a later chapter.</p>
<p>Finally, humans cannot directly read BAM files, or even decompress them with standard Unix tools. If you want to view a BAM file, you can use <code>samtools view</code> to read it in SAM format.</p>
</section>
<section id="quick-self-study" class="level3" data-number="9.4.8">
<h3 data-number="9.4.8" class="anchored" data-anchor-id="quick-self-study"><span class="header-section-number">9.4.8</span> Quick self study</h3>
<ol type="1">
<li>Suppose a read is Read 2 from the FASTQ, it aligns to the reverse strand, and its mate does too. The alignment is a primary alignment, but it has been flagged as a PCR duplicate. Write down, in hexadecimal form, all the bits that will be set for this read’s alignment, then combine them to compute the SAM FLAG for it.</li>
<li>Given the alignments shown below, what do you think the CIGAR strings for Read 1 and Read 2 might look like?</li>
</ol>
<pre><code>      Read 2:  5'  ACCT--AGGAGGACACACAC   3' 
5'  ACATAGACAGGGACCACCTGCAGGA---CACACACGCAGGTTTACTAAGGGTTTACTCAACACAGTGAACAGCATATACCAGA  3'  
forward-strand
    |||||||||||||||||||||||||---|||||||||||||||||||||||||||||||||||||||||||||||||||||||
reverse-strand
3'  TGTATCTGTCCCTGGTGGACGTCCT---GTGTGTGCGTCCAAATGATTCCCAAATGAGTTGTGTCACTTGTCGTATATGGTCT  5'
                                      Read 1:  3' AAAAAAAAAAAATTGTGTC-CT  5'</code></pre>
</section>
</section>
<section id="variants" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="variants"><span class="header-section-number">9.5</span> Variants</h2>
<p>Most conservation geneticists who started working in the field before the genomic revolution will recognize <em>variant</em> data as being most similar to what they have traditionally thought of as “genotype data” or, simply, “the data.” As the name implies, variant data consist of data only at those places in the genome where there is variation within a population or a species. This variation is the informative portion of the data for many analyses. In other words, you needn’t always carry with you information about every single base in the genome, because at most positions in the genome, every individual you are studying will carry the same base, and such fixed sites are not informative for many genetic analyses.</p>
<p>On the one hand, you can think of sites with no variation as being a little like monomorphic microsatellite loci (if that analogy is helpful for our older, more experienced, readers, who have been doing conservation genetics for a while…) Typically, such monomorphic loci were dropped for many analyses. On the other hand, when you are sampling genetic variation from an entire genome, it is also very useful to be able to keep track of how many sites in the genome are variable versus not variable. Accordingly,with genomic variant data it is important to keep track of how many variants exists within a given portion of the genome, so, we must keep track of <em>where</em>, within our reference genome, the variant sites are.</p>
<p>Finally, decades ago, many of the different types of genetic variant data were a reflection of the methodology used to assay them. So, for example, restriction-fragment length polymorphisms and amplified fragment length polymorphisms were somewhat crude summaries that were responsive to differences in the underlying sequences of bases, but were only telling us about sequence at a very small (like 6 bp) section of the genome). Meanwhile minisatellites and microsatellites were expressed in terms of the number of repeated short motifs in a location of the genome, without telling us what the sequence there actually was. Today, however, with the resolution provided by genome sequencing, many such polymorphisms that were defined by gross or summarized features of the sequence can now be categorized and described in terms of the actual genome sequence carried by the two copies of a chromosome in a diploid individual. The variants in this context are define according to how those sequences differ from the corresponding sequence in the reference genome. The latter point bears repeating: currently, variant data are defined in terms of differences between the sequence carried by an individual and the genome sequence as it is listed in the reference genome.</p>
<p>(We note that there is exciting work on developing a more “de-centralized” notion of variation data: one in which variants are not defined as departures from a “canonical” reference genome, but rather one in which all the known variation is recorded in a single “genomic variation graph.” This has exciting possibilities for reducing biases that might arise from the use of a single reference genome; however its use in conservation genetics is still likely a few (or more) years distant.)</p>
<p>The resolution of genetic data now allows us to define many different kinds of polymorphisms in terms of the sequence data itself. At the same time, just as the instruments used to gather sequence data can attach a variety of additional information (like base-quality and mapping scores) to sequence data, the methods used to infer the variants carried by an individual also may provide an abundance of additional information that should remain attached to the genotypes of individuals. Further, as is a constant theme in genomics, the scale of variant data one can obtain is huge and we will often want to access information about only certain defined subsets of the variants carried by any particular individual. And finally, as more data gets collected, we will want to be able to combine data from different sources and studies and use the combined data in a unified fashion.</p>
<p>For all the above reasons, the genomics community has recognized the need for a flexible and extensible format for storing variant data. Developing such a format and helping it to evolve as new types of genomic data allow new types of variants to be recorded, has been a major focus, driven largely by research in human genetics. For the most part, this community has converged on a format known as Variant Call Format or VCF. This format makes it possible to do all of the following:</p>
<ol type="1">
<li>Record variants such as SNPs, and short insertions and deletions, in a single framework, in terms of the sequences carried by individuals. (There is also now support for reording large structural variations and copy number variations; however, those have not, as yet, become central in conservation genetics).</li>
<li>Attach to each particular locus or variant an arbitrary quantity of extra information, which might include confidence/quality scores or annotation information (which genes is the variant in), etc.</li>
<li>Attach to each particular inferred genotype of an individual a variety of information such as confidence scores, read depth, haplotypic phase, etc.</li>
<li>Compress all of the data in an efficient fashion and still allow the data to be processed (by some utilities) without uncompressing the data.</li>
<li>Index the data so that fast access to information about specific genomic regions can be extracted quickly.</li>
</ol>
<p>The flexibility and extensibility of the VCF format comes with a small cost to conservation genomicists in that the format might look like nothing you have ever seen before! On top of that, if you want to work with VCF files, you really ought to learn to use specialized tools that have been developed for handling VCF files. This turns out to be essential in conservation genomics for the simple reason that even if you don’t end up doing most of your own bioinformatics (i.e.&nbsp;you leave the alignment and variant calling to a genotyping/bioinformatics service (or to a graduate student or postdoc)), the chances are good that whomever does that for you will (or, at least, <em>should</em>) send results to you in a VCF file. So, while you might be able to do work in conservation genomics without ever having to crack open a BAM file, or parse the lines of a FASTQ file, you will almost invariably have to bang your head against a VCF file at some point.</p>
<p>So, what I am saying, is don’t be a complete noob like I was in 2011 when I received my first data set in VCF format. I didn’t have any idea what it was, and after wracking my brain over it finally wrote back to the genotyping service that had sent it to me:</p>
<pre><code>I have looked over the file and everything makes sense save for a few 
things.   I was hoping you could answer just a few (should be easy) 
questions.  You went over this when we videoconferenced, but just a 
few things are hazy. Sorry.

QUAL column:  How is this scaled? There are 13990 distinct values 
ranging from 6.2 to 250.64.  Is it just sort of relative?  What is 
"good" quality.

The INFO column:  what does this mean: "NS=22:AN=1:DP=541"

In other words what are NS, AN, and DP?

The FORMAT column.  Looking at the file it appears that 
"GT:DP:GQ:EC:SG" means that the first field is a genotype (0,1, or 
0/1, for homozygous reference, homozygous non-reference, and 
heterozygous).  And SG must be the IUPAC code for the individual's 
genotype, but what are DP, GQ, and EC?  If I had to hazard a guess I 
would say:
DP = # of reads with reference base
GQ = # of reads total whether or not they overlapped the position of 
the base in question
EC = # of reads with alternate base</code></pre>
<p>Hah! I just put that out there to remind myself that VCF files will seem super mysterious to <em>everyone</em> when they first encounter them. My goal in the next section is to help you be better informed than I was when I saw my first VCF file. So, with that in mind, let’s jump into learning about the format…</p>
<section id="vcf-format-the-body" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="vcf-format-the-body"><span class="header-section-number">9.5.1</span> VCF Format – The Body</h3>
<p>VCF files, just like SAM files, have a header section and a main “body” section. We will start by describing the body section, in which each row holds information about a variant and the genotypes carried by individuals in a sample. We will discuss the header section after that.</p>
<p>To download a VCF file that you might view in a text editor you can use this link:</p>
<ul>
<li><a href="https://www.dropbox.com/s/dzwixabvy3wwfdr/chinook-32-3Mb.vcf.gz?dl=1">https://www.dropbox.com/s/dzwixabvy3wwfdr/chinook-32-3Mb.vcf.gz?dl=1</a></li>
</ul>
<p>If you want to, you can decompress that file and open it with an <em>able</em> text editor (like TextWrangler or BBedit on a Mac or Notepad++ on Windows). Don’t open it with MS Word! Also, on you laptop, <em>don’t try to just double click it!</em> The .vcf extension is often interpreted as a “Virtual Contact File”, meaning that your computer will try to open it—and possibly try to import it—using whatever program you handle your contacts’ phone numbers and addresses with.</p>
<p>To get download the “index” for that file, use this:</p>
<ul>
<li><a href="https://www.dropbox.com/s/d303fi7en71p8ug/chinook-32-3Mb.vcf.gz.csi?dl=1">https://www.dropbox.com/s/d303fi7en71p8ug/chinook-32-3Mb.vcf.gz.csi?dl=1</a></li>
</ul>
<p>If you want to download these onto a remote Unix server you can use:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wget</span> https://www.dropbox.com/s/dzwixabvy3wwfdr/chinook-32-3Mb.vcf.gz<span class="pp">?</span>dl=1</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wget</span> https://www.dropbox.com/s/d303fi7en71p8ug/chinook-32-3Mb.vcf.gz.csi<span class="pp">?</span>dl=1</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># after which you might need to rename them, if wget retained the `?dl=1`</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># in the resulting file names:</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mv</span> chinook-32-3Mb.vcf.gz<span class="dt">\?</span>dl<span class="dt">\=</span>1 chinook-32-3Mb.vcf.gz</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mv</span> chinook-32-3Mb.vcf.gz.csi<span class="dt">\?</span>dl<span class="dt">\=</span>1 chinook-32-3Mb.vcf.gz.csi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>At their core, VCF files are TAB-delimited text files. Below is a fragment of a VCF file body (and the final header line) holding information about 9 variants (in 9 rows below the final header line) and the genotypes at those variants carried in four individuals (the four right-most columns).</p>
<pre><code>#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  DPCh_plate1_A05_S5  DPCh_plate1_A06_S6  DPCh_plate1_A11_S11 DPCh_plate1_A12_S12
NC_037124.1 4001417 .   T   G   1528.4  .   AC=14;AF=0.245;AN=44;BaseQRankSum=2.296;ClippingRankSum=-1.168;DP=206;FS=0;MLEAC=51;MLEAF=0.236;MQ=60;MQRankSum=1.501;QD=23.88;ReadPosRankSum=1.685;SOR=0.608   GT:AD:DP:GQ:PL  1/1:0,1:1:3:45,3,0  ./.:.:.:.:. 0/0:1,0:1:3:0,3,46  ./.:.:.:.:.
NC_037124.1 4001912 .   A   G   4886.98 .   AC=29;AF=0.652;AN=48;BaseQRankSum=4.315;ClippingRankSum=-0.984;DP=220;FS=0.753;MLEAC=139;MLEAF=0.662;MQ=59.92;MQRankSum=0.311;QD=29.62;ReadPosRankSum=-1.071;SOR=0.737  GT:AD:DP:GQ:PL  0/0:1,0:1:3:0,3,46  ./.:.:.:.:. 0/1:3,1:4:33:33,0,120   1/1:0,2:2:6:87,6,0
NC_037124.1 4004574 .   AAAGG   A   957.91  .   AC=12;AF=0.176;AN=48;BaseQRankSum=1.052;ClippingRankSum=0.887;DP=201;FS=0;MLEAC=28;MLEAF=0.149;MQ=60;MQRankSum=0.73;QD=26.61;ReadPosRankSum=-1.135;SOR=0.591    GT:AD:DP:GQ:PL  1/1:0,1:1:3:45,3,0  ./.:.:.:.:. 0/0:2,0:2:6:0,6,119 0/0:2,0:2:6:0,6,109
NC_037124.1 4006558 .   T   TG  3442.71 .   AC=24;AF=0.56;AN=28;BaseQRankSum=-1.068;ClippingRankSum=-1.509;DP=191;FS=5.394;MLEAC=102;MLEAF=0.554;MQ=60;MQRankSum=-0.621;QD=29.42;ReadPosRankSum=0.552;SOR=0.464 GT:AD:DP:GQ:PL  ./.:.:.:.:. 1/1:0,2:2:6:75,6,0  1/1:0,2:2:6:82,6,0  ./.:.:.:.:.
NC_037124.1 4006887 .   G   T   109.29  .   AC=2;AF=0.048;AN=40;BaseQRankSum=-0.411;ClippingRankSum=-0.145;DP=175;FS=0;MLEAC=6;MLEAF=0.032;MQ=60;MQRankSum=-0.718;QD=15.61;ReadPosRankSum=-0.502;SOR=1.323  GT:AD:DP:GQ:PL  0/0:2,0:2:6:0,6,90  ./.:.:.:.:. 0/0:1,0:1:3:0,3,46  0/0:1,0:1:3:0,3,42
NC_037124.1 4007343 .   T   TGGAAGGAAGGAAACG    7696.07 .   AC=42;AF=0.985;AN=42;BaseQRankSum=2.278;ClippingRankSum=1.604;DP=213;FS=0;MLEAC=192;MLEAF=0.99;MQ=60;MQRankSum=0.139;QD=31.22;ReadPosRankSum=0.973;SOR=0.7  GT:AD:DP:GQ:PL  ./.:.:.:.:. 1/1:0,1:1:3:34,3,0  ./.:.:.:.:. 1/1:0,1:1:9:135,9,0
NC_037124.1 4007526 .   C   T   1040.07 .   AC=13;AF=0.17;AN=54;BaseQRankSum=1.507;ClippingRankSum=0.333;DP=227;FS=2.374;MLEAC=35;MLEAF=0.165;MQ=60;MQRankSum=2.562;QD=17.05;ReadPosRankSum=1.567;SOR=0.679 GT:AD:DP:GQ:PL  0/1:1,1:2:19:19,0,39    0/0:1,0:1:3:0,3,45  0/0:2,0:2:6:0,6,49  0/0:2,0:2:6:0,6,90
NC_037124.1 4007583 .   C   CAA 596.58  .   AC=3;AF=0.084;AN=54;BaseQRankSum=-0.197;ClippingRankSum=-0.445;DP=224;FS=0;MLEAC=19;MLEAF=0.089;MQ=60;MQRankSum=0.096;QD=20.57;ReadPosRankSum=-1.754;SOR=1.127  GT:AD:DP:GQ:PL  ./.:.:.:.:. 0/0:1,0:1:3:0,3,45  0/0:2,0:2:6:0,6,90  0/0:1,0:1:3:0,3,45
NC_037124.1 4007584 .   GCC G,CCC   3246.17 .   AC=3,25;AF=0.083,0.324;AN=54;BaseQRankSum=1.157;ClippingRankSum=-0.459;DP=227;FS=2.342;MLEAC=16,56;MLEAF=0.074,0.259;MQ=60;MQRankSum=0.412;QD=28.98;ReadPosRankSum=-0.656;SOR=0.527 GT:AD:DP:GQ:PL  ./.:.:.:.:. 2/2:0,0,1:1:3:37,39,45,3,3,0    2/2:0,0,2:2:6:82,84,90,6,6,0    2/2:0,0,1:1:3:45,45,45,3,3,0</code></pre>
<p>Wow! That is really hard to look at. The column corresponding to the INFO field is quite long and obtrusive. Below we turn that column into a <code>.</code> in every row:</p>
<pre><code>#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  DPCh_plate1_A05_S5  DPCh_plate1_A06_S6  DPCh_plate1_A11_S11 DPCh_plate1_A12_S12
NC_037124.1 4001417 .   T   G   1528.4  .   .   GT:AD:DP:GQ:PL  1/1:0,1:1:3:45,3,0  ./.:.:.:.:. 0/0:1,0:1:3:0,3,46  ./.:.:.:.:.
NC_037124.1 4001912 .   A   G   4886.98 .   .   GT:AD:DP:GQ:PL  0/0:1,0:1:3:0,3,46  ./.:.:.:.:. 0/1:3,1:4:33:33,0,120   1/1:0,2:2:6:87,6,0
NC_037124.1 4004574 .   AAAGG   A   957.91  .   .   GT:AD:DP:GQ:PL  1/1:0,1:1:3:45,3,0  ./.:.:.:.:. 0/0:2,0:2:6:0,6,119 0/0:2,0:2:6:0,6,109
NC_037124.1 4006558 .   T   TG  3442.71 .   .   GT:AD:DP:GQ:PL  ./.:.:.:.:. 1/1:0,2:2:6:75,6,0  1/1:0,2:2:6:82,6,0  ./.:.:.:.:.
NC_037124.1 4006887 .   G   T   109.29  .   .   GT:AD:DP:GQ:PL  0/0:2,0:2:6:0,6,90  ./.:.:.:.:. 0/0:1,0:1:3:0,3,46  0/0:1,0:1:3:0,3,42
NC_037124.1 4007343 .   T   TGGAAGGAAGGAAACG    7696.07 .   GT:AD:DP:GQ:PL  ./.:.:.:.:. 1/1:0,1:1:3:34,3,0  ./.:.:.:.:. 1/1:0,1:1:9:135,9,0
NC_037124.1 4007526 .   C   T   1040.07 .   .   GT:AD:DP:GQ:PL  0/1:1,1:2:19:19,0,39    0/0:1,0:1:3:0,3,45  0/0:2,0:2:6:0,6,49  0/0:2,0:2:6:0,6,90
NC_037124.1 4007583 .   C   CAA 596.58  .   .   GT:AD:DP:GQ:PL  ./.:.:.:.:. 0/0:1,0:1:3:0,3,45  0/0:2,0:2:6:0,6,90  0/0:1,0:1:3:0,3,45
NC_037124.1 4007584 .   GCC G,CCC   3246.17 .   .   GT:AD:DP:GQ:PL  ./.:.:.:.:. 2/2:0,0,1:1:3:37,39,45,3,3,0    2/2:0,0,2:2:6:82,84,90,6,6,0    2/2:0,0,1:1:3:45,45,45,3,3,0</code></pre>
<p>Phew! That is easier on the eyes at this point. Looking at the above, notice that the first <em>nine columns</em> carry information that pertains to the variant itself (i.e., the SNP or the indel that is being described in this row). These nine columns are followed by four columns, each one pertaining to one of the four samples whose names are given in the top row: <code>DPCh_plate1_A05_S5    DPCh_plate1_A06_S6  DPCh_plate1_A11_S11 DPCh_plate1_A12_S12</code>.</p>
<p>We will start by describing the 9 standard variant-specific columns:</p>
<ol type="1">
<li><code>CHROM</code>: the name of the reference sequence upon which the variant was found. This comes from the FASTA file that was used as a reference to align the sequencing data to, orinally.</li>
<li><code>POS</code>: The 1-based position within <code>CHROM</code> that the variant is found at. For SNPs, this is straightforward. For insertions and deletions it is also straightforward, but you must remember that the value in the <code>POS</code> columns give the first position in the entry in the <code>REF</code> column. More on that below…</li>
<li><code>ID</code>: An identifier for a particular variant. These identifiers are used to indicate the name of the variant in different data bases, like the human dbSNP data base. For non-model organisms of conservation concern, there are typically no such data bases, so the values in this column will be “missing” which is always denoted by a single period, <code>.</code>, in a VCF file.</li>
<li><code>REF</code> the sequence of the reference—i.e.&nbsp;the “reference allele” at the variant. See below for more description about how this is designated.</li>
<li><code>ALT</code> the sequence of the alternate allele(s) at the variant. If there is more than one alternate allele at the variant, the sequences for each are separated by a comma. (See more below).</li>
<li><code>QUAL</code>: a Phred-scaled assessment of whether the variant truly represents variation in the sample that was sequenced and genotyped, or whether it might be a spurious variant—for example, not a true polymorphism, but rather due to a sequencing error. If an alternate allele is given in <code>ALT</code>, then the QUAL is <span class="math inline">\(-10\log_{10} P(\mathrm{there~truly~is~NOT~such~an~alternate~allele(s)})\)</span>. A larger number means more confidence that the alternate allele is real. If there is no alternate allele given in <code>ALT</code> (i.e.&nbsp;the <code>ALT</code> field holds a <code>.</code>), then the value in QUAL is <span class="math inline">\(-10\log_{10} P(\mathrm{there~actually~IS~a~variant~here})\)</span>.</li>
<li><code>FILTER</code>: a semicolon-delimited list of filters that this variant tests positive for. This provides a way of creating different possible sets of variants that can be tagged in different ways, but not removed from the data set. Not used extensively in conservation genomics.</li>
<li><code>INFO</code>: a semicolon-delimited list of “key=value” pairs that describe properties of the variant. GATK attaches a large number of these. The meaning of different keys is given in the header (see below).</li>
<li><code>FORMAT</code>: this is a column that says, “In the remaining columns, information about the genotypes of different individuals will be given in the following fields separated by colons.” It is basically a key to deciphering the following columns of the genotype data of the individuals, <em>in that row</em>. Specifying the genotype column formats <em>for each row</em>, in this fashion, makes it possible to attach different types of information to different variants, as might be appopriate.</li>
</ol>
<section id="coding-of-ref-and-alt" class="level4" data-number="9.5.1.1">
<h4 data-number="9.5.1.1" class="anchored" data-anchor-id="coding-of-ref-and-alt"><span class="header-section-number">9.5.1.1</span> Coding of REF and ALT</h4>
<p>When coding for insertions and deletions—or for more complex variants in which some of the insertions might carry SNPs, etc.—the convention is followed that the <code>REF</code> column always shows the sequence in the reference sequence <em>starting at</em> <code>POS</code>. For understanding how insertions and deletions are encoded in this system, it is helpful to view them in columnar format with positions running down the first column, and different alleles in different columns. Thus, a simple SNP, such as the first row in the above VCF example would appear as:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># meaning of: NC_037124.1 4001417 .   T   G </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="ex">pos</span>         Ref  Alt</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="ex">4001417</span>     T      G</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>By contrast, an insertion, relative to the reference genome, creates bases that don’t have a standard coordinate that they align to. Thus, if we take the second-to-last variant in the above example (at position 4007583), and we assume that positions 4007582 and 4007584 in the reference sequence are a G and a T, respectively, then the first five columns of the row indicate that the variation appears as follows:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># meaning of: NC_037124.1 4007583 .   C   CAA</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="ex">Pos</span>         Ref  Alt</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="ex">4007582</span>     G    G</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="ex">4007583</span>     C    C</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="bu">.</span>           <span class="at">-</span>    A</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="bu">.</span>           <span class="at">-</span>    A</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="ex">4007584</span>     T    T</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>where the <code>-</code> represents an insertion relative to the reference genome.</p>
<p>A deletion relative to the reference genome, like that in the third row of the above example: would appear in columnar format as:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># meaning of: NC_037124.1 4004574 .   AAAGG   A</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="ex">Pos</span>         Ref  Alt</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="ex">4004573</span>     C    C</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="ex">4004574</span>     A    A</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="ex">4004575</span>     A    <span class="at">-</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="ex">4004576</span>     A    <span class="at">-</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="ex">4004577</span>     G    <span class="at">-</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="ex">4004578</span>     G    <span class="at">-</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="ex">4004579</span>     T    T</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>where we are imagining that the reference holds a C at position 4004573 and a T at position 4004579, and where the <code>-</code>’s indicate deletions relative to the reference.</p>
<p>Finally, the multiallelic and complex example on the last row, in columnar format, if the reference held an A at position 4007583 and a T at position 4007587, would show the two possible alternate alleles like:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># meaning of: NC_037124.1 4007584 .   GCC G,CCC</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="ex">Pos</span>         Ref   Alt1  Alt2</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="ex">4007583</span>     A     A     A</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="ex">4007584</span>     G     G     C</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="ex">4007585</span>     C     <span class="at">-</span>     C</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="ex">4007586</span>     C     <span class="at">-</span>     C</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="ex">4007587</span>     T     T     T</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="the-genotype-columns" class="level4" data-number="9.5.1.2">
<h4 data-number="9.5.1.2" class="anchored" data-anchor-id="the-genotype-columns"><span class="header-section-number">9.5.1.2</span> The Genotype Columns</h4>
<p>Each of the columns after the 9th column correspond to genotype information at a single one of the samples. The <code>FORMAT</code> string for each in the example is: <code>GT:AD:DP:GQ:PL</code>. There could be more fields than these five (and, if so, information about those fields will be stored in the header section of the VCF file); however, these five are pretty standard, and will be described here. For a concrete example, we will focus in the following on the genotype column for the first sample on the third line from the bottom (POS = 4007526):</p>
<pre><code>0/1:1,1:2:19:19,0,39</code></pre>
<p>Broken into the five fields we would see:</p>
<ol type="1">
<li><code>GT</code> = <code>0/1</code> — The <code>GT</code> stands for <em>GenoType</em>. This field gives the “called” genotype of the individual as two alleles (0 and 1, here) separated by either a <code>/</code> or a <code>|</code>. The <code>0</code> always refers to the reference allele (<code>REF</code>), and a number greater than 0 refers to an alternate allele (from the <code>ALT</code> column). If there are only two alleles, (a reference allele and one alternate allele) then the alternate allele will always be denoted by a 1. If there are two alternate alleles, the two alternate alleles will be denoted as 1 and 2, respectively.
<ul>
<li><p>A <code>/</code> means that the two gene copies are not <em>phased</em>—in other words, it is not known which <em>haplotype</em> they occur on.</p></li>
<li><p>A <code>|</code> as the separator means that the two gene copies in the individual are recorded as being phased. If an indiduals <code>GT</code> field in a series of variants looks like:</p>
<p>::: {.cell}</p>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="dv">0</span><span class="sc">|</span><span class="dv">1</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">|</span><span class="dv">0</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">|</span><span class="dv">0</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">|</span><span class="dv">1</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="dv">0</span><span class="sc">|</span><span class="dv">0</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">|</span><span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<p>Then this is recording that on one of the (diploid) individual’s two chromosomes, the alleles would be strung along like: <code>0-1-1-1-0-1</code>, and the other chromosome would carry the alleles strung along like: <code>1-0-0-1-0-1</code>.<br>
</p></li>
</ul></li>
<li><code>AD</code> = <code>1,1</code> — The <code>AD</code> stands for <em>Allele Depth</em>. This field gives the comma-separated depths of reads from the individual that carried the different alleles at this position. In this case there are only two alleles (a REF and an ALT), so that there is one comma separating two values. The <code>1</code> before the comma says that we saw one read with the REF allele, and the <code>1</code> after the comma says that we saw one read that had the ALT allele. If there is more than one ALT allele, then there will be more commas, each one separating a different allele read depth (i.e., REF,ALT1,ALT2,etc). These values can sometimes be extracted and used in place of the actual genotypes for making inferences (for example, doing PCAs or computing Fst values using <em>single read sampling</em>).</li>
<li><code>DP</code> = <code>2</code> — The <code>DP</code> denotes <em>DePth</em>. This field gives the total number of reads from this individual mapped on top of this position. It is typically the sum of the allele depths, but not always, owing to some reads indicating an allele at the position that the variant caller might have deemed a sequening error, etc. In general, the greater the read depth, the more confidence you can have in the genotype calls. Though it might be worthwhile to focus on the read depth itself to identify variants in repetitive regions or copy-number variation.</li>
<li><code>GQ</code> = <code>19</code> — The <code>GQ</code> stands for <em>Genotype Quality</em>. This field gives a Phred scaled measure of confidence in the genotype call. This value is given conditional on there actually being a variant (in the population) at this position. Thus, it says, “If we set aside the question of whether or not the variant we see here is real, its genotype quality is given by <span class="math inline">\(-10\log_{10} P(\mathrm{the~genotype~call~is~wrong})\)</span>.” So, colloquially, the probability that the genotype recorded for the individual is incorrect is <span class="math inline">\(10^{-GQ/10}\)</span>. So, if GQ = 19, we have (ostensibly) the probability that the genotype call is incorrect equalling <span class="math inline">\(10^{-19/10} = 0.0126\)</span>. These probabilities must be taken with a grain of salt. Often, the raw genotype calls from low-ish coverage sequencing data can be somewhat more error prone.<br>
</li>
<li><code>PL</code> = <code>19,0,39</code> — <code>PL</code> stands for</li>
</ol>
</section>
</section>
<section id="vcf-format-the-header" class="level3" data-number="9.5.2">
<h3 data-number="9.5.2" class="anchored" data-anchor-id="vcf-format-the-header"><span class="header-section-number">9.5.2</span> VCF Format – The Header</h3>
<p>Let’s just get in there and take a look at it.</p>
</section>
<section id="boneyard" class="level3" data-number="9.5.3">
<h3 data-number="9.5.3" class="anchored" data-anchor-id="boneyard"><span class="header-section-number">9.5.3</span> Boneyard</h3>
<p>VCF. I’ve mostly used vcftools until now, but I’ve gotta admit that the interface is awful with all the –recode BS. Also, it is viciously slow. So, let’s just skip it all together and learn how to use bcftools. One nice thing about bcftools is that it works a whole lot like samtools, syntactically.</p>
<p>Note that for a lot of the commands you need to have an indexed vcf.gz.</p>
</section>
</section>
<section id="segments" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="segments"><span class="header-section-number">9.6</span> Segments</h2>
<p>BED</p>
</section>
<section id="conversionextractions-between-different-formats" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="conversionextractions-between-different-formats"><span class="header-section-number">9.7</span> Conversion/Extractions between different formats</h2>
<ul>
<li>vcflib’s vcf2fasta takes a phased VCF file and a fasta file and spits out sequence.</li>
</ul>
</section>
<section id="visualization-of-genomic-data" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="visualization-of-genomic-data"><span class="header-section-number">9.8</span> Visualization of Genomic Data</h2>
<p>Many humans, by dint of our evolution, are exceptionally visual creatures. Being able to create visual maps for different concepts is also central facilitating understanding of those concepts and extending their utility to other realms. The same is true for bioinformatic data: being able to visualize bioinformatic data can help us understand it better and to see connections between parts of our data sets that we did not, before.</p>
<p>The text-based bioinformatic formats we have discussed so far do not, standing by themselves, offer a rich visual experience (have you ever watched a million lines of a SAM file traverse your terminal, and gotten much understanding from that?). However, sequence data, once it has been aligned to a reference genome has an “address” or “genomic coordinates” that, by analogy to street addresses and geographic coordinates suggests that aligned sequence data might be visualized like geographic data in beautiful and/or thought-provoking “maps.”</p>
<p>There are a handful of programs that do just that: they make compelling, interactive pictures of bioinformatic data. One of those programs (that I am partial to), called IGV (for Integative Genomics Viewer), was developed in the cross-platform language, Java, by researchers at the Broad Institute. It is available for free download from <a href="https://software.broadinstitute.org/software/igv/">https://software.broadinstitute.org/software/igv/</a>, and it should run on almost any operating system. It has been well-optimized to portray genomics data at various scales and to render an incredible amount of information in visual displays as well as text-based “tool-tip” reports that may be activated by mousing over different parts of the display.</p>
<p>There is extensive documentation that goes with IGV, but it is valuable (and more fun!) to just crack open some genomic data and start playing with it. To do so, there are just a few things that you need to know:</p>
<ol type="1">
<li><p>The placement of all data relies on the reference genome as a sort of “base map.” The reference genome serves the purpose of a latitude-longitude coordinate system that lets you make sense of spatial data on maps. Therefore, it is required for all forays with IGV. You must specify a reference genome by choosing one of the options from the “Genomes” menu. If you are working on a non-model organism of conservation concern it is likely that you will have the reference genome for that critter on your local computer, so you would “Genomes-&gt;Load Genome From File…”, to show IGV where the FASTA file (cannot be compressed) of your genome is on your hard drive. Let’s repeat that: if you are loading the FASTA for a reference genome into IGV, you <em>must</em> use the “Genomes” menu option. If you use “<strong>File</strong>-&gt;Load From File…” to try to load the reference genome, it won’t let you. Don’t do it! Use “<strong>Genomes-&gt;Load Genome From File</strong>”</p></li>
<li><p>Once your reference genome is known to IGV, you can add data from the bioinformatic formats described in this chapter <em>that include positions from a reference genome</em>. These include SAM or BAM files and VCF files (but note FASTQ files). To include data from these formats, choose “File-&gt;Load From File…”. (Note, BAMs are best sorted and indexed). The data from each file that you “Load” in this manner appears in a separate <em>track</em> of data in a horizontally tiled window that is keyed to the reference genome coordinates.</p></li>
<li><p>You can zoom in and out as appropriate (and in several different ways).</p></li>
<li><p>Right clicking within any track gives a set of options appropriate for the type of track it is. For example, if you are viewing a BAM file, you can choose whether the reads joined together with their mates (“View as pairs”) or not, or whether the alignments should be viewed at “full scale” (“Expanded”), somewhat mashed down (“Collapsed”) or completely squashed down and small (“Squished”).</p></li>
</ol>
<section id="sample-data" class="level3" data-number="9.8.1">
<h3 data-number="9.8.1" class="anchored" data-anchor-id="sample-data"><span class="header-section-number">9.8.1</span> Sample Data</h3>
<p>About 0.5 Gb of sample data can be downloaded from <a href="https://drive.google.com/file/d/1TMug-PjuL7FYrXRTpNikAgZ-ElrvVneH/view?usp=sharing">https://drive.google.com/file/d/1TMug-PjuL7FYrXRTpNikAgZ-ElrvVneH/view?usp=sharing</a>.</p>
<p>This download includes a zip-compressed folder called <code>tiny-genomic-data</code>. Within that folder are two more folders:</p>
<ul>
<li><code>chinook-wgs-3-Mb-on-chr-32</code>: FASTQs, BAMs, and VCFs from whole genome sequencing data along a 3 Mb span of Chinook salmon chromosome 32 (which in the reference is named <code>NC_037124.1</code>). The genomic region from which the data comes from is <code>NC_037124.1:4,000,000-7,000,000</code>. The BAM and VCF files can be viewed against the reference genome in IGV.</li>
<li><code>mykiss-rad-and-wgs-3-Mb-chr-omy28</code> includes BAMs from RAD-seq data (sequenced in the study by <span class="citation" data-cites="princeEvolutionaryBasisPremature2017">[@princeEvolutionaryBasisPremature2017]</span>) from multiple steelhead trout individuals merged together into two BAM files. The genomic region included in those BAM files is omy28:11,200,000-12,200,000. Also included is a VCF file from whole genome resequencing data from 125 steelhead and rainbow trout in the 3 Mb region from `omy28:10,150,000-13,150,000.</li>
</ul>
<p>Both of the above directories include a <code>genome</code> directory that holds the FASTA that you must point IGV to. Note that in neither case does the FASTA hold the complete genome of the organism. I have merely included three chromosomes in each—the chromosome upon which the BAM and VCF data are located, and the chromosome on either side of that chromosome.</p>
<p>Explore these data and have fun. Some things to play with (remember to right-click [cntrl-click on a Mac] each track for a menu) :</p>
<p>Start with the Chinook data:</p>
<ol type="1">
<li>Load the FASTA for each data set first</li>
<li>Load a BAM file after that</li>
<li>Then load a VCF file.</li>
<li>You will likely have to zoom pretty far into a genomic region with data (see above!) before you see anything interesting.</li>
<li>Try zooming in as far as you can.</li>
<li>Toggle “View as Pairs” and see the result.</li>
<li>Play with “Collapsed/Expanded/Squished”</li>
<li>Experiment with grouping/sorting/coloring alignments by different properties</li>
<li>Use coloring to quickly find alignments with
<ul>
<li><code>F1R2</code> of <code>F2R1</code> orientation</li>
<li>Insert size &gt; 1000 bp</li>
</ul></li>
<li>Sort by mapping quality and find some reads with MAPQ &lt; 60</li>
<li>Zoom out and use the VCF to find a region with a high variant density, then zoom back in and view the alignments there? What do you notice about the number of reads aligning to those areas?</li>
</ol>
<p>For the steelhead data additionally:</p>
<ol type="1">
<li>Do you see where the RAD cutsite must have been and how paired-end sequencing works from either side of the cutsite?</li>
<li>What do you notice about the orientation of Read 1 and Read 2 on either side of the cutsite?</li>
<li>Why do we see the read depth patterns we see on either side of the cutsite? (i.e., in many cases it goes up as you move away from the cutsite, and then drops off again.)</li>
<li>Do you appreciate this visual representation of how sparse RAD data is compared to whole genome resequencing data?</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../nmfs-bioinf/snake.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Snakemake Tutorial Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../nmfs-bioinf/sequence-alignment.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sequence alignment and handling BAM files</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>